CREATE TABLE sandwich (
    `id` VARCHAR(255),
    `nom` VARCHAR(255),
    `description` VARCHAR(255),
    `type_pain` VARCHAR(255),
    `img` VARCHAR(255)
);
INSERT INTO sandwich VALUES ('10','ab-fuga','Et tenetur praesentium nulla facere officia et. Consequatur quasi aperiam qui enim vel. Maiores nemo dolor aliquid et architecto ea voluptas at.','tortillas','null');
INSERT INTO sandwich VALUES ('11','vitae-in','Sed consequatur nobis est. Et et cupiditate ipsam sequi earum sint non. Qui incidunt magnam tempora quas eum qui.','pain complet','null');
INSERT INTO sandwich VALUES ('12','impedit-qui','Aut aut rem exercitationem voluptates qui. Qui soluta aut minus dolor est. Sequi cum quos vel placeat.','baguette','null');
INSERT INTO sandwich VALUES ('13','similique-sed','Rerum ipsa nihil et aut possimus. Autem et aut eos odit. Maxime consequuntur nemo facilis atque culpa et.','mie','null');
INSERT INTO sandwich VALUES ('14','qui-corporis','Asperiores velit ut voluptatem magni et voluptatem. Illum aut possimus iste. Beatae ut ipsa aut dolores mollitia explicabo molestias.','mie','null');
INSERT INTO sandwich VALUES ('15','nihil-qui','Veritatis voluptatem culpa et et autem itaque. Quos neque in aut esse facere consequuntur. Ab in repellat ut voluptatem ullam fugiat odit.','tortillas','null');
INSERT INTO sandwich VALUES ('16','sapiente-soluta','Vel tempore est quae velit. Adipisci delectus itaque molestias voluptatem numquam libero libero accusamus. Aut delectus blanditiis non ab consequatur.','baguette campagne','img/c83871837e68cc38e6fb7fd0b904bb59.png');
INSERT INTO sandwich VALUES ('17','tempore-omnis','Ut qui perferendis est expedita aut iste. Illo id libero impedit sunt. Ut aliquid et qui unde at est.','tortillas','null');
INSERT INTO sandwich VALUES ('18','mollitia-omnis','Est reiciendis a illo voluptate. Expedita soluta autem iure. Voluptatum id nemo quos optio recusandae quia iure.','mie','img/7589799de870ef7f71a6173879c53130.png');
INSERT INTO sandwich VALUES ('19','quo-est','Voluptatibus accusamus dolorem velit assumenda. Quo dolor ab autem deserunt necessitatibus et. Quisquam quas voluptas et quas perspiciatis aut rerum.','mie','null');
INSERT INTO sandwich VALUES ('20','aperiam-voluptas','Quae neque iusto fugiat omnis non alias dolore voluptatem. Beatae praesentium adipisci et corrupti accusamus nesciunt ullam vel. Et repudiandae asperiores quo impedit perspiciatis possimus accusantium.','mie','null');
INSERT INTO sandwich VALUES ('21','quis-dolorem','Qui numquam possimus fugiat et quaerat. Nobis sapiente porro aliquam et. Quam voluptas qui iste et reprehenderit.','baguette','null');
INSERT INTO sandwich VALUES ('22','adipisci-sed','Vero blanditiis quis non iusto dolor incidunt. Sint temporibus vitae dolore veniam. Necessitatibus molestias vel aut eius non.','mie','null');
INSERT INTO sandwich VALUES ('24','dolor-perspiciatis','Incidunt laudantium illo esse molestiae magnam. Eum quia facere hic dolorem doloribus assumenda. Recusandae quae nesciunt provident voluptatum molestiae voluptatem vitae.','baguette','null');
INSERT INTO sandwich VALUES ('25','ducimus-sunt','Consequatur maiores reiciendis unde. Consequuntur nihil aliquam explicabo aut magnam et. Natus unde quia quia molestias.','pain complet','null');
INSERT INTO sandwich VALUES ('26','laborum-ad','Beatae non reiciendis expedita itaque cupiditate odit rerum consequuntur. Exercitationem earum voluptatem accusantium ipsam dolore mollitia non inventore. Iure dolor velit asperiores optio optio non iure.','pain complet','null');
INSERT INTO sandwich VALUES ('27','accusantium-omnis','Est ut et id perferendis placeat cumque. Provident qui perspiciatis in in distinctio. Ea sit nihil nihil.','baguette campagne','img/5842d14c195888425c82fd1d7f135516.png');
INSERT INTO sandwich VALUES ('28','beatae-quaerat','Vero vero tempore veniam aut. Repellat itaque velit illum consequatur sint eos. Delectus eos sunt dolorum autem blanditiis eius quis dolores.','tortillas','null');
INSERT INTO sandwich VALUES ('29','ea-qui','Dolore quod dicta ut quisquam placeat. Deleniti velit eius quis sit sunt neque architecto. Perspiciatis quae voluptas tenetur qui at sunt vel.','mie','null');
INSERT INTO sandwich VALUES ('30','expedita-quo','Nostrum quia qui voluptatum ad. Delectus omnis eveniet modi. Qui dolorem soluta consequuntur iusto.','pain complet','null');
INSERT INTO sandwich VALUES ('31','laboriosam-eos','Neque sit molestiae necessitatibus voluptas ad voluptatem voluptatem. Corporis inventore nam et dolorem odit ea quisquam enim. Pariatur ad dolorem laborum voluptatem.','tortillas','null');
INSERT INTO sandwich VALUES ('32','quod-deleniti','Eligendi aut atque id quia. Unde sed doloremque suscipit ut quia ipsam. Ipsa aliquid quidem et in enim exercitationem voluptatum sequi.','mie','img/114d1c2d4c030dc1118bc16cbe2b05cc.png');
INSERT INTO sandwich VALUES ('33','sit-enim','Ea veritatis facere debitis aperiam adipisci corporis et. Eum libero asperiores atque voluptatem. Distinctio assumenda illo est soluta voluptatem ea expedita.','tortillas','null');
INSERT INTO sandwich VALUES ('34','mollitia-ipsum','Molestiae voluptatem in impedit praesentium autem ex. Doloribus explicabo magni dolor consequuntur cupiditate aliquid voluptate. Corporis nulla voluptatem dolor ut aut facilis minima.','pain complet','null');
INSERT INTO sandwich VALUES ('35','modi-cum','Et nihil qui vero non facilis quasi. Libero ut est qui non quos. Voluptates voluptatem quia quasi sit id dolor quaerat.','tortillas','null');
INSERT INTO sandwich VALUES ('36','dolorum-aut','Sequi dolorem quas sed nostrum. Non quas molestias et sunt aliquam tenetur mollitia corrupti. Ut sit libero rem magni.','pain complet','img/1dc4d4bcfccd4735194236f04d4d1f66.png');
INSERT INTO sandwich VALUES ('37','itaque-natus','Dolorem architecto dolorem et. Et voluptatum fugiat voluptas quia saepe sed dolore. Non esse quia ea.','pain complet','img/742673b0d81bc75f520f472c8566d3b7.png');
INSERT INTO sandwich VALUES ('38','unde-qui','Voluptatem autem expedita non molestias. Magni accusantium harum adipisci iste eum. Reprehenderit suscipit est nihil et esse id perferendis quo.','baguette','null');
INSERT INTO sandwich VALUES ('39','architecto-minus','Non ut aperiam dolore excepturi velit voluptatum. Tenetur nihil reprehenderit voluptatem voluptates non. Debitis magni explicabo sit.','baguette campagne','null');
INSERT INTO sandwich VALUES ('40','laudantium-voluptates','Consequatur reprehenderit ut ipsa in et reprehenderit eum. Incidunt dolores sed odit et corporis dignissimos omnis. Autem nihil vero odio repellendus voluptas ipsam.','baguette','img/c2d740de94f7d483bdde260494ab67fc.png');
INSERT INTO sandwich VALUES ('41','corrupti-sapiente','Saepe omnis harum temporibus. Enim quia qui at et aut reiciendis saepe non. Ex assumenda totam expedita qui voluptatem eveniet totam.','mie','null');
INSERT INTO sandwich VALUES ('42','et-nesciunt','Dolor culpa distinctio harum ut. Consequatur quis soluta id nemo. Ea alias eum est earum.','mie','null');
INSERT INTO sandwich VALUES ('43','sit-dolor','Aliquam autem et non. Error quia et sed at dolores repellendus. Libero quia repellat debitis minus est.','tortillas','img/cdc30e3970df46144adfa63e7e6b1595.png');
INSERT INTO sandwich VALUES ('44','voluptas-rerum','Ipsum perspiciatis nihil eos sint. Voluptas voluptate non ut laborum molestiae. Veritatis beatae cupiditate non optio.','baguette','img/a317714831e45c52deee048a48b1c892.png');
INSERT INTO sandwich VALUES ('45','consectetur-commodi','Vero ut consequatur voluptas in et maxime. Distinctio vitae totam voluptatum debitis in consectetur recusandae. Facilis nihil sed voluptatem delectus quod minus facere provident.','tortillas','null');
INSERT INTO sandwich VALUES ('46','minima-omnis','Eos autem deserunt assumenda magni suscipit. Ut ut qui porro et. Quos consequatur mollitia veniam vitae.','pain complet','img/991594dbfc3736a9c2622cf00112399f.png');
INSERT INTO sandwich VALUES ('47','est-modi','Ex veritatis fugit temporibus ipsa alias velit a et. Qui voluptas aut ipsam quidem nostrum odit cumque praesentium. Velit expedita reiciendis commodi ea cupiditate aut.','baguette','null');
INSERT INTO sandwich VALUES ('48','inventore-in','Dolorem cumque molestiae voluptate error ut vero. Aut exercitationem dicta dicta nihil sapiente porro. Consequatur iure enim velit impedit nisi sunt.','baguette','null');
INSERT INTO sandwich VALUES ('49','temporibus-ipsam','Consequatur maiores id tenetur. Rerum quos mollitia similique sint omnis autem enim. Exercitationem necessitatibus aspernatur sequi aperiam minus.','tortillas','null');
INSERT INTO sandwich VALUES ('50','perspiciatis-dolorum','Quas numquam minus cumque perferendis non quisquam. A magnam aut aut sint. Alias rem aut a nam.','baguette campagne','null');
INSERT INTO sandwich VALUES ('51','molestiae-ratione','Ut velit similique dolorum blanditiis. Doloribus sint ipsa esse in eligendi possimus. Omnis laboriosam ipsum praesentium voluptatem.','mie','img/07fb4b5dc6a0425929a4b877205cebb3.png');
INSERT INTO sandwich VALUES ('52','veniam-voluptas','Quisquam dolores minus tempora dolores rem officia dolor ratione. Tenetur nemo quis veniam consequuntur rerum incidunt voluptas velit. Sed eius est id inventore odio.','baguette','null');
INSERT INTO sandwich VALUES ('53','est-vero','Aut aut aliquam odit minus corrupti omnis eos. Omnis et repellendus quis dolorum. Modi non ratione accusantium.','tortillas','null');
INSERT INTO sandwich VALUES ('54','repellendus-vitae','Sint est incidunt esse officia consequuntur dolorum. Vitae ut non ab voluptas officia expedita adipisci. Autem qui harum sint recusandae.','pain complet','null');
INSERT INTO sandwich VALUES ('55','eligendi-eius','Ea consequatur quis dicta sit sed. Cumque illo dolores ab molestiae non blanditiis. Sit eum unde ratione explicabo repudiandae.','mie','null');
INSERT INTO sandwich VALUES ('56','nihil-maiores','Id nesciunt aut dolorem ea repudiandae. Voluptatem quia et officiis et. Maxime sit enim ex ad aut velit.','pain complet','null');
INSERT INTO sandwich VALUES ('57','eaque-nostrum','Enim fuga sequi quis aspernatur. Rerum beatae vel aliquam qui nihil id. Illum doloribus culpa ad praesentium ex.','baguette campagne','null');
INSERT INTO sandwich VALUES ('58','nulla-consequuntur','Omnis consequatur quod possimus. Autem harum possimus harum laborum eligendi qui. Eligendi et dolorem id dolores.','baguette','img/83916726e811c8de722d057d02812fdd.png');
INSERT INTO sandwich VALUES ('59','ipsum-impedit','Vero libero rem voluptas qui. Inventore similique itaque neque explicabo autem. Voluptatibus aperiam qui qui hic sunt et.','pain complet','img/b047421fe8adcb89b8a0d938f29eb6da.png');
INSERT INTO sandwich VALUES ('60','odio-quis','Est consequatur quasi inventore rerum. Aliquam fuga dolor id adipisci delectus. Vero quo ut enim dignissimos et doloribus quis dolores.','pain complet','null');
INSERT INTO sandwich VALUES ('61','laboriosam-ut','Aut adipisci maxime ut sed temporibus. Delectus repellat sint expedita et maiores. Voluptatem dolores rerum vel molestias velit sed modi deleniti.','baguette','img/ed392cf0faa69cc967d6ac8d9b9cbfb4.png');
INSERT INTO sandwich VALUES ('62','officiis-ducimus','Rerum explicabo ducimus culpa dolores. Asperiores error illo maxime qui libero modi est. Sit eum recusandae aut et quos.','baguette','null');
INSERT INTO sandwich VALUES ('63','aperiam-et','Tempore sequi est eos facere soluta voluptatem recusandae. Necessitatibus aliquid quae necessitatibus rerum maiores enim in. Vel voluptatem ut delectus.','tortillas','null');
INSERT INTO sandwich VALUES ('64','ut-laboriosam','Voluptatem et quae molestiae aut et voluptas. Ducimus non culpa quia voluptas non debitis. Eos velit laborum dolor.','tortillas','img/16d085eb2d4d8730f8c07be498ceee64.png');
INSERT INTO sandwich VALUES ('65','sunt-minus','Quos officia ea provident. Reprehenderit sunt et aspernatur minima facere quod nulla. Cupiditate aliquid numquam architecto laborum tempora in est.','baguette','img/d8df6f4d770664f76a847ebcf395f1fa.png');
INSERT INTO sandwich VALUES ('66','laboriosam-qui','Nemo commodi voluptas rerum molestiae ut assumenda dolor. Aut qui aut nemo aliquam facilis consectetur. Quidem possimus aut est corporis qui voluptas suscipit.','pain complet','null');
INSERT INTO sandwich VALUES ('67','rem-doloribus','Nobis voluptates commodi autem et beatae tempore. Ut sit natus recusandae eum recusandae. Qui temporibus ipsam dolores dolor esse quod.','pain complet','null');
INSERT INTO sandwich VALUES ('68','eius-vel','Accusamus aspernatur harum enim deleniti est. Officiis consequuntur sapiente expedita commodi laboriosam recusandae. Debitis repellat et voluptas eos ipsam.','pain complet','null');
INSERT INTO sandwich VALUES ('69','quia-quas','Assumenda doloremque ut explicabo aut esse et vero. Et accusamus explicabo debitis est consectetur. Quisquam voluptas dicta aperiam laboriosam sit.','pain complet','img/52ab422d125a222a57986dfbec5c64f8.png');
INSERT INTO sandwich VALUES ('70','sit-expedita','Quo perspiciatis tempora et quis reprehenderit esse sapiente. Mollitia illo repellendus culpa et. Deserunt pariatur voluptatem pariatur autem quidem aut rem.','baguette','img/e112e7284b1258058776999219be05c0.png');
INSERT INTO sandwich VALUES ('71','molestiae-minima','Dolorem cupiditate maxime quia aut autem et libero. Ducimus qui qui fugit sed voluptatem odit atque iusto. Error iste at eum consequuntur qui et.','pain complet','null');
INSERT INTO sandwich VALUES ('72','beatae-suscipit','Asperiores voluptatem excepturi velit et. Rerum molestiae cumque quas tenetur et eveniet. Quaerat optio autem earum omnis sequi voluptas.','baguette campagne','img/12b3f9d041d62611d539fbebf2eda05a.png');
INSERT INTO sandwich VALUES ('73','dicta-sint','Ea maxime id temporibus rem enim. Aut dolor sed asperiores illum nesciunt quisquam ut. Animi sed sed autem quia beatae non.','baguette','null');
INSERT INTO sandwich VALUES ('74','ut-praesentium','Et magnam omnis amet nesciunt consectetur ipsa. Ratione magni sed possimus ut sed. At sit perferendis eos commodi voluptas omnis minus fugiat.','mie','null');
INSERT INTO sandwich VALUES ('75','doloribus-non','Est assumenda voluptas hic possimus recusandae repellat quis. Eum dignissimos libero illo illum id illum earum. Molestiae quibusdam hic iusto non.','baguette','img/c8ff58e7a299d8d01b1a69ac2cb7f5a5.png');
INSERT INTO sandwich VALUES ('76','aut-iusto','Explicabo quia quia officiis. Pariatur quam qui nostrum ut inventore. Rerum corporis voluptatum illum expedita quam neque fugit.','tortillas','null');
INSERT INTO sandwich VALUES ('77','nihil-debitis','Veniam sed ullam quasi quibusdam. Et illo sit dicta possimus. Eum praesentium esse a ipsa dolor neque deleniti quia.','pain complet','null');
INSERT INTO sandwich VALUES ('78','tenetur-debitis','Exercitationem fuga eaque ex autem libero. Necessitatibus totam aut est molestiae. Voluptatem suscipit laboriosam est qui natus qui nemo.','mie','img/548dbc719a32fb75e627bb5ec88c1efe.png');
INSERT INTO sandwich VALUES ('79','error-aut','Quos qui officia voluptatem alias. Aut optio corrupti corrupti velit fugit. Voluptatem et neque omnis doloribus accusamus facilis.','pain complet','null');
INSERT INTO sandwich VALUES ('80','dolorem-dolorem','Soluta et labore delectus quisquam et ullam et. Vel unde delectus qui modi. Distinctio et ex sint qui dolor eos blanditiis libero.','baguette campagne','img/38853c71a4167ee6e3f6bf0433cca2b5.png');
INSERT INTO sandwich VALUES ('81','et-odit','Sunt et laudantium ducimus qui et excepturi ratione sit. Ab maxime labore sed ipsam officiis. Sit saepe autem incidunt et omnis nulla odio enim.','mie','img/960684bbdef89b240b5fa221493f60ba.png');
INSERT INTO sandwich VALUES ('82','nostrum-eligendi','Nostrum rerum voluptas quia repellendus et odio libero. Ipsa aliquid ipsum eligendi porro consequuntur nisi assumenda. Quam ratione reiciendis non vitae deserunt distinctio.','mie','img/916e5a135ebc72c38de6f2fe35bc211a.png');
INSERT INTO sandwich VALUES ('83','nesciunt-distinctio','Ipsam ratione at consequuntur modi ut. Ex odio sint molestiae id at quam cumque. Dolor laborum alias a repellat dolor qui et.','mie','null');
INSERT INTO sandwich VALUES ('84','magni-autem','In beatae eos dolorem aliquam est vero iste. Harum adipisci velit quod impedit fugiat. Exercitationem repellat asperiores dolor officiis laboriosam facilis id.','baguette campagne','null');
INSERT INTO sandwich VALUES ('85','sit-impedit','Deserunt cumque animi dolores iure. Et delectus non assumenda officia id dignissimos. Est velit quasi eum facilis accusamus.','mie','img/151d76856fb9fa716fdede9b57ea00ec.png');
INSERT INTO sandwich VALUES ('86','maxime-ut','Ducimus aut sed facere ratione. Quia voluptatibus iusto voluptatem quod. Atque vel iure repellendus ipsum sed exercitationem recusandae.','baguette campagne','img/f12957e5266616b1d7532323cc2de738.png');
INSERT INTO sandwich VALUES ('87','odit-illum','Inventore accusantium qui est totam quis. Voluptates sit reprehenderit debitis officiis et et aut. Saepe atque qui quae quod velit.','mie','img/886718da90e0bb0167bd3cae8e8fbebb.png');
INSERT INTO sandwich VALUES ('88','in-est','Et omnis molestiae vitae hic qui corrupti. Sit suscipit quo non architecto dolores deserunt. Eum minus sed quis.','baguette campagne','null');
INSERT INTO sandwich VALUES ('89','ipsum-hic','Sit quam culpa sit sapiente magni voluptas nihil. Eaque architecto provident aperiam aliquid voluptatem. Quod minus maxime et ut aliquid quis consectetur.','baguette','img/4fe256dfeadfaa91951e6a81fd40921b.png');
INSERT INTO sandwich VALUES ('90','rerum-magnam','Qui ut est distinctio aliquid. Velit voluptatem aliquam odit. Numquam magni consequuntur fugiat amet dolor asperiores.','tortillas','null');
INSERT INTO sandwich VALUES ('91','aspernatur-hic','Dolorum eos consequatur blanditiis expedita dolores. Modi ut deserunt libero in veritatis repellat et. Nostrum nesciunt aut voluptatum minus qui exercitationem tempora aut.','baguette campagne','null');
INSERT INTO sandwich VALUES ('92','placeat-consequuntur','Reprehenderit nihil eum quidem nostrum maiores. Beatae placeat et voluptas ducimus voluptatum adipisci blanditiis aliquid. Sit fuga adipisci sequi autem sit voluptates.','pain complet','img/e8a000fbe0bb1a78b9d2119fea1047a6.png');
INSERT INTO sandwich VALUES ('93','reiciendis-sint','Atque praesentium rerum numquam. Id ut et consequatur dolorem. Rerum eum necessitatibus officia rerum sed minus quia.','pain complet','null');
INSERT INTO sandwich VALUES ('94','sint-aut','Nam dicta in repudiandae et recusandae distinctio. Sunt deleniti nesciunt eveniet impedit beatae blanditiis nisi. Molestias deserunt iusto reiciendis ut dolorem.','pain complet','null');
INSERT INTO sandwich VALUES ('95','distinctio-ad','Sunt in aut at corrupti. Quaerat nihil explicabo sapiente aut adipisci. Cupiditate dicta voluptas quibusdam nihil accusamus et.','baguette campagne','null');
INSERT INTO sandwich VALUES ('96','voluptas-molestiae','Voluptatum omnis optio ad odio ratione quos magnam. Illum et qui non iure. Dicta itaque quos harum quo quo omnis.','tortillas','img/5fcb5797776b4acddcc3114599050d06.png');
INSERT INTO sandwich VALUES ('97','et-at','Inventore necessitatibus et autem voluptatibus quia eos. Molestias eaque voluptatum velit cum nulla repellat ut sit. Animi ut doloribus laudantium modi.','tortillas','null');
INSERT INTO sandwich VALUES ('98','rerum-pariatur','Et quae minus ipsa illum. Voluptas eligendi sit et praesentium assumenda beatae dolorum. Culpa exercitationem ducimus deserunt incidunt.','tortillas','null');
INSERT INTO sandwich VALUES ('99','voluptatibus-tempora','Repellat exercitationem aspernatur expedita delectus autem quibusdam iure. Assumenda ut natus pariatur dolorem eos architecto qui reprehenderit. Quam sit natus magnam similique maxime.','baguette','img/1e794d57abb56ea407a77c56bcc37197.png');
INSERT INTO sandwich VALUES ('100','explicabo-quia','Est necessitatibus sit inventore. Nihil culpa eos quaerat ipsa rem modi facere. At aut sed nesciunt inventore est ut.','pain complet','img/4f96a002444be86d244e4f7159a29dc6.png');
INSERT INTO sandwich VALUES ('101','ducimus-voluptates','Dolorem dolorum adipisci ut in. Esse et consequatur tenetur dolor. Asperiores dolorem facilis voluptatum recusandae.','mie','img/44fbc36c5ec08cc6c3c0e49272c5c684.png');
INSERT INTO sandwich VALUES ('102','consequatur-aspernatur','Qui aliquam voluptas et et sit quo. Mollitia iusto dolorum natus ut sed vitae nihil ut. Nostrum aperiam dolore corporis placeat.','baguette','null');
INSERT INTO sandwich VALUES ('103','aspernatur-commodi','In ut et voluptatem ad non necessitatibus omnis. Id aliquam praesentium nam. Laborum animi illum delectus est explicabo id quis.','mie','img/f33bdb70d55794baf46aa398386853b2.png');
INSERT INTO sandwich VALUES ('104','eaque-similique','Distinctio et et repellat dolores qui nihil. Quia nobis et eius vel. Autem assumenda magnam qui qui placeat.','mie','img/10062116ad39a09919a97f41a1a13f2b.png');
INSERT INTO sandwich VALUES ('105','dolores-facilis','Sit et modi eligendi eum modi quia provident. Qui dolor rerum repellat voluptates. Voluptas eligendi sint nihil iusto eum.','mie','null');
INSERT INTO sandwich VALUES ('106','eos-omnis','Sunt culpa sapiente temporibus dolorum aspernatur omnis. Et unde sed aspernatur est. Quisquam dolorum velit natus perspiciatis ut.','pain complet','img/8e4971b29216225b039f07ffcf8c964d.png');
INSERT INTO sandwich VALUES ('107','asperiores-inventore','Atque ad eos a beatae. Doloribus nemo ipsam dolore vero. Maiores nam porro sit.','tortillas','null');
INSERT INTO sandwich VALUES ('108','velit-est','Quia sit qui eaque doloremque mollitia eveniet aut excepturi. Ut sed velit doloribus. Quia qui dolor velit quo nostrum debitis perferendis.','baguette','null');
INSERT INTO sandwich VALUES ('109','ipsum-in','Ipsa occaecati nam dolores autem assumenda. Et nihil odit ut nihil et aut ut. Rem et ut adipisci fugit voluptatem.','baguette campagne','null');
INSERT INTO sandwich VALUES ('110','dolores-voluptatem','Delectus et deleniti libero blanditiis iste beatae. Consequatur ut ut magni iure qui accusantium id. Corporis illum illum aut atque tenetur aut.','baguette','null');
INSERT INTO sandwich VALUES ('111','non-dolor','Sunt non porro facere maiores. Enim porro voluptate nostrum aliquam facilis. Sed aut blanditiis qui.','pain complet','img/f660903077e0dbd42af9ebad86b31373.png');
INSERT INTO sandwich VALUES ('112','et-rerum','Quidem exercitationem est suscipit omnis. Numquam dignissimos cumque porro voluptatem. Placeat cum sequi dolorum voluptates consectetur repellat quidem.','baguette','null');
INSERT INTO sandwich VALUES ('113','aut-dolorem','Consequuntur temporibus dolor quibusdam iure fuga est. Ut unde suscipit corrupti odio dolores velit. Aut aut quis qui non dolorem voluptatem qui.','tortillas','null');
INSERT INTO sandwich VALUES ('114','accusamus-voluptas','Rerum et in quis voluptas. Hic fugiat nobis maxime suscipit eligendi rerum. Dolorum officia nihil asperiores ipsa.','pain complet','null');
INSERT INTO sandwich VALUES ('115','est-excepturi','Sunt voluptatem est autem dolorem qui expedita. Dolores qui quis nam et officiis dolor. Sunt ratione quia in at est omnis temporibus.','tortillas','null');
INSERT INTO sandwich VALUES ('116','délice de la mer','le bon sandwich au saumon','mie','null');
INSERT INTO sandwich VALUES ('fcf208e0-86b4-430c-b5a9-1c32ab15ffff','testsdf','testsdf','testsdf','testsdf');
INSERT INTO sandwich VALUES ('f21fb705-149a-4ae1-8103-8e86eb90c31d','qsdq','qq','testsqqdf','qqqq');
INSERT INTO sandwich VALUES ('80483585-8993-4378-9eb6-f1e601137576','test','test','test',NULL);
INSERT INTO sandwich VALUES ('d060fd29-d447-4e61-855c-5ed79769893d','test','test','test',NULL);
INSERT INTO sandwich VALUES ('f6244c30-1519-43eb-b97b-44ca36a9796f','test','test','test',NULL);
INSERT INTO sandwich VALUES ('ced0f950-8fd3-4705-8886-90ed820acf1d','test','test','test',NULL);
INSERT INTO sandwich VALUES ('2b530209-fa8f-40a7-bff5-39b38c6bb980','test','test','test',NULL);
INSERT INTO sandwich VALUES ('10cc7db4-5747-4d60-939c-d8bb72bc1f91','test','test','test',NULL);
INSERT INTO sandwich VALUES ('7d87431c-e3a5-48a2-819c-cf8b52e0acc7','test','test','test',NULL);
INSERT INTO sandwich VALUES ('04d0bd67-f0ac-4105-803f-694f646a2895','bio','un sandwich bio','bio',NULL);
INSERT INTO sandwich VALUES ('54db2363-5adb-4e59-982f-f947e61364e6','bio','un sandwich bio','bio',NULL);
INSERT INTO sandwich VALUES ('22726779-1d3a-4820-a7fd-d62dc2145abe','bio','un sandwich bio','bio',NULL);
INSERT INTO sandwich VALUES ('e452c58a-d51f-4944-847d-2e297aba5e7b','bio','un sandwich bio','bio',NULL);
INSERT INTO sandwich VALUES ('bf8625c0-3fbb-46f5-9cac-55b8dbe8de11','ab-<wx<wx<wxw<xw<','4','<wx<w',NULL);
INSERT INTO sandwich VALUES ('05601b6b-3efc-4141-8bdf-0417f30a8b5e','bio','un sandwich bio','bio',NULL);
INSERT INTO sandwich VALUES ('05cbecbc-618f-4882-abde-ff6ea1e765ed','test','test','test',NULL);
INSERT INTO sandwich VALUES ('a4466df1-503d-479d-9b89-ef5d0c6f4425','test','test','test',NULL);
INSERT INTO sandwich VALUES ('4137bde5-ec3f-4b19-8dd1-670da0e05add','test','test','test',NULL);
INSERT INTO sandwich VALUES ('6d6b8360-ca43-436c-a55f-5c4d020b9d31','test','test','test',NULL);
INSERT INTO sandwich VALUES ('c645544f-9a53-4244-a259-36e43f917063','test','test','test',NULL);
INSERT INTO sandwich VALUES ('cf050fdc-a2eb-4bb2-aee5-fe27f1cb96a5','bio','un sandwich bio','bio',NULL);
INSERT INTO sandwich VALUES ('c01c046a-1196-43a5-a231-0a5a04d031f7','bio','un sandwich bio','bio',NULL);
